apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  labels:
    app: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: frontend:2
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: BackendApiUrl
          value: "http://host.docker.internal:8081/"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    app: weatherapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
  labels:
    app: weatherapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: backend:2
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: weatherfacade
  labels:
    app: weatherfacade
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
  selector:
    app: weatherapp