name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for web
      run: docker build . --file ./website/Dockerfile --tag shop-website:$(date +%s)
    - name: Build the Docker image for api
      run: docker build . --file ./product/Dockerfile --tag product-api:$(date +%s)
